# Multivariate Regression

Let's grab a small little data set of Blue Book car values:

In [4]:
import pandas as pd

df = pd.read_excel('cars.xls')

In [5]:
df

,Price,Mileage,Make,Model,Trim,Type,Cylinder,Liter,Doors,Cruise,Sound,Leather
0,17314.103129,8221,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,1
1,17542.036083,9135,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0
2,16218.847862,13196,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0
3,16336.913140,16342,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,0,0
4,16339.170324,19832,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,0,1
5,15709.052821,22236,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0
6,15230.003390,22576,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0
7,15048.042184,22964,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,0
8,14862.093870,24021,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,0,1
9,15295.018267,27325,Buick,Century,Sedan 4D,Sedan,6,3.1,4,1,1,1
10,21335.852485,10237,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,0,0
11,20538.087510,15066,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,0
12,20512.094091,16633,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,0
13,19924.159052,19800,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,1
14,19774.249066,23359,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,1
15,19344.165537,23765,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,0
16,19105.130124,24008,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,0,0
17,18543.427045,26034,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,1
18,17808.198996,32896,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,0
19,17968.838278,34665,Buick,Lacrosse,CX Sedan 4D,Sedan,6,3.6,4,1,1,1
20,22358.877678,8970,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,1,0
21,23785.922526,10577,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,1,1
22,22926.090371,14363,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,1,1
23,21895.758784,16508,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,0,1
24,21273.061714,18908,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,0,0
25,21460.013953,19467,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,0,1
26,21183.123587,21394,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,0,0
27,20406.099503,22596,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,0,0
28,21058.139580,24469,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,1,1
29,19556.899320,25245,Buick,Lacrosse,CXL Sedan 4D,Sedan,6,3.6,4,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
774,14568.002255,18511,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,1
775,13122.905457,19101,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,1
776,13494.288783,19500,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,1,0,1
777,12036.216751,19853,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,1
778,12162.140047,21770,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,0
779,12333.603993,21877,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,0,0
780,12099.014578,22758,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,1,1,0
781,12119.089702,22826,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,0,1
782,11679.923546,23388,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,0,0
783,13216.912048,24069,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,0
784,12412.521107,24664,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,1
785,12284.288290,24740,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,1,1,0
786,12594.183013,26328,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,0,1
787,12105.981336,28298,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,0
788,11873.533995,28398,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,0,0
789,12965.223269,29707,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,1
790,10563.066162,32458,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,0,0
791,11413.530403,32619,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,1,0,1
792,11504.824550,33962,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,0,0
793,11521.525888,34998,Saturn,Ion,Sedan 4D,Sedan,4,2.2,4,0,1,1
794,18173.978084,5826,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,1
795,18490.983029,7755,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,1
796,17322.078404,10102,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,0,1
797,17978.356998,10986,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,0,0
798,16425.174796,14242,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,0,0
799,16507.070267,16229,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,0,0
800,16175.957604,19095,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,0
801,15731.132897,20484,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,0
802,15118.893228,25979,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,1,0
803,13585.636802,35662,Saturn,L Series,L300 Sedan 4D,Sedan,6,3.0,4,1,0,0

We can use pandas to split up this matrix into the feature vectors we're interested in, and the value we're trying to predict.

Note how we use pandas.Categorical to convert textual category data (model name) into an ordinal number that we can work with.

In [6]:
import statsmodels.api as sm

df['Make_ord'] = pd.Categorical(df.Make).codes
X = df[['Mileage', 'Make_ord', 'Doors']]
y = df[['Price']]

X1 = sm.add_constant(X)
est = sm.OLS(y, X1).fit()

est.summary()

ModuleNotFoundError: No module named 'statsmodels'

The table of coefficients above gives us the values to plug into an equation of form:
    B0 + B1 * Mileage + B2 * model_ord + B3 * doors
    
But in this example, it's pretty clear that mileage is more important than anything based on the std err's.

Could we have figured that out earlier?

In [4]:
y.groupby(df.Doors).mean()

              Price
Doors
2      23807.135520
4      20580.670749

Surprisingly, more doors does not mean a higher price! So it's not surprising that it's pretty useless as a predictor here. This is a very small data set however, so we can't really read much meaning into it.

## Activity

Mess around with the fake input data, and see if you can create a measurable influence of number of doors on price. Have some fun with it - why stop at 6 doors?