In [8]:
import pandas

In [10]:
df = pandas.DataFrame([[1,2,3],[4,5,6]])

In [13]:
df

   0  1  2
0  1  2  3
1  4  5  6

In [15]:
print(df)

   0  1  2
0  1  2  3
1  4  5  6

In [2]:
df = pandas.read_csv("steak-risk-survey.csv")

NameError: name 'pandas' is not defined

In [2]:
import pandas
df = pandas.read_csv("steak-risk-survey.csv")
df

,RespondentID,"Consider the following hypothetical situations: <br>In Lottery A, you have a 50% chance of success, with a payout of $100. <br>In Lottery B, you have a 90% chance of success, with a payout of $20. <br><br>Assuming you have $10 to bet, would you play Lottery A or Lottery B?",Do you ever smoke cigarettes?,Do you ever drink alcohol?,Do you ever gamble?,Have you ever been skydiving?,Do you ever drive above the speed limit?,Have you ever cheated on your significant other?,Do you eat steak?,How do you like your steak prepared?,Gender,Age,Household Income,Education,Location (Census Region)
0,NaN,Response,Response,Response,Response,Response,Response,Response,Response,Response,Response,Response,Response,Response,Response
1,3.237566e+09,Lottery B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.234982e+09,Lottery A,No,Yes,No,No,No,No,Yes,Medium rare,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,East North Central
3,3.234973e+09,Lottery A,No,Yes,Yes,No,Yes,Yes,Yes,Rare,Male,> 60,"$150,000+",Graduate degree,South Atlantic
4,3.234972e+09,Lottery B,Yes,Yes,Yes,No,Yes,Yes,Yes,Medium,Male,> 60,"$50,000 - $99,999",Bachelor degree,New England
5,3.234959e+09,Lottery B,No,Yes,No,No,Yes,Yes,Yes,Medium,Male,> 60,"$50,000 - $99,999",Graduate degree,Middle Atlantic
6,3.234955e+09,Lottery A,No,No,No,No,Yes,No,Yes,Medium rare,Male,18-29,"$0 - $24,999",Some college or Associate degree,West South Central
7,3.234955e+09,Lottery A,No,Yes,No,No,Yes,Yes,No,NaN,Male,> 60,"$150,000+",Graduate degree,New England
8,3.234955e+09,Lottery A,No,Yes,Yes,Yes,Yes,No,Yes,Medium rare,Male,18-29,"$25,000 - $49,999",Some college or Associate degree,West North Central
9,3.234953e+09,Lottery A,Yes,Yes,Yes,No,Yes,No,Yes,Medium,Male,18-29,"$50,000 - $99,999",Bachelor degree,East North Central
10,3.234951e+09,Lottery B,No,Yes,Yes,No,No,No,Yes,Medium rare,Male,> 60,"$25,000 - $49,999",Some college or Associate degree,Pacific
11,3.234949e+09,Lottery B,No,Yes,No,No,Yes,No,Yes,Medium rare,Male,> 60,"$50,000 - $99,999",High school degree,South Atlantic
12,3.234948e+09,Lottery A,No,No,Yes,No,Yes,No,Yes,Medium rare,Male,18-29,"$100,000 - $149,999",Graduate degree,Middle Atlantic
13,3.234947e+09,Lottery B,No,Yes,Yes,Yes,Yes,No,Yes,Medium,Male,18-29,"$50,000 - $99,999",Bachelor degree,West South Central
14,3.234947e+09,Lottery A,Yes,Yes,Yes,No,Yes,No,Yes,Rare,Male,18-29,"$50,000 - $99,999",Graduate degree,Pacific
15,3.234945e+09,Lottery B,No,Yes,No,Yes,Yes,No,Yes,Medium Well,Male,> 60,"$50,000 - $99,999",Bachelor degree,Pacific
16,3.234944e+09,Lottery A,No,Yes,No,No,Yes,No,Yes,Medium Well,Male,18-29,"$25,000 - $49,999",Some college or Associate degree,Mountain
17,3.234942e+09,Lottery A,No,Yes,Yes,No,Yes,No,Yes,Medium,Male,18-29,"$50,000 - $99,999",Bachelor degree,South Atlantic
18,3.234941e+09,Lottery B,No,Yes,No,No,Yes,No,No,NaN,Male,18-29,"$0 - $24,999",Some college or Associate degree,Pacific
19,3.234939e+09,Lottery A,No,Yes,Yes,No,No,No,Yes,Medium rare,Male,18-29,"$50,000 - $99,999",Bachelor degree,West North Central
20,3.234938e+09,Lottery B,Yes,Yes,No,No,Yes,No,No,NaN,Male,18-29,"$150,000+",Some college or Associate degree,East North Central
21,3.234938e+09,Lottery B,No,No,No,No,Yes,No,Yes,Medium rare,Male,30-44,"$50,000 - $99,999",Graduate degree,South Atlantic
22,3.234938e+09,Lottery A,No,Yes,Yes,No,Yes,No,Yes,Medium rare,Male,18-29,"$25,000 - $49,999",Bachelor degree,West North Central
23,3.234937e+09,Lottery A,Yes,Yes,Yes,No,Yes,No,Yes,Medium Well,NaN,NaN,NaN,NaN,NaN
24,3.234937e+09,Lottery B,No,No,No,No,Yes,No,Yes,Medium rare,Male,> 60,"$25,000 - $49,999",Some college or Associate degree,Middle Atlantic
25,3.234936e+09,Lottery B,No,No,No,No,Yes,No,Yes,Medium rare,Male,45-60,"$0 - $24,999",Some college or Associate degree,East North Central
26,3.234936e+09,Lottery A,Yes,Yes,Yes,No,Yes,No,Yes,Medium Well,Male,18-29,"$50,000 - $99,999",High school degree,West North Central
27,3.234935e+09,Lottery B,No,Yes,No,No,Yes,No,Yes,Medium,Male,45-60,"$25,000 - $49,999",Bachelor degree,West South Central
28,3.234933e+09,Lottery B,Yes,Yes,Yes,No,No,No,Yes,Medium rare,Male,45-60,"$50,000 - $99,999",Graduate degree,Middle Atlantic
29,3.234932e+09,Lottery A,No,Yes,No,No,Yes,No,Yes,Medium,Male,> 60,"$25,000 - $49,999",Graduate degree,East North Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,3.234770e+09,Lottery A,No,Yes,Yes,No,Yes,No,Yes,Medium,Female,30-44,"$50,000 - $99,999",Some college or Associate degree,New England
522,3.234770e+09,Lottery A,No,No,Yes,No,Yes,No,Yes,Medium Well,Female,30-44,"$0 - $24,999",Some college or Associate degree,West South Central
523,3.234769e+09,Lottery A,No,Yes,Yes,No,Yes,No,No,NaN,Female,18-29,NaN,Bachelor degree,East North Central
524,3.234768e+09,Lottery B,No,Yes,Yes,NaN,Yes,Yes,No,NaN,Female,30-44,"$50,000 - $99,999",Some college or Associate degree,West South Central
525,3.234768e+09,Lottery B,No,Yes,Yes,No,Yes,No,Yes,Medium rare,Female,30-44,"$100,000 - $149,999",Graduate degree,East North Central
526,3.234768e+09,Lottery A,Yes,Yes,Yes,No,Yes,No,Yes,Medium,Female,30-44,"$50,000 - $99,999",Some college or Associate degree,South Atlantic
527,3.234767e+09,Lottery B,No,Yes,No,No,No,Yes,Yes,Well,Male,30-44,"$0 - $24,999",Some college or Associate degree,East North Central
528,3.234766e+09,Lottery B,Yes,Yes,Yes,Yes,Yes,No,No,NaN,Female,30-44,"$0 - $24,999",Some college or Associate degree,Pacific
529,3.234766e+09,Lottery B,Yes,No,Yes,No,Yes,Yes,No,NaN,Female,30-44,"$25,000 - $49,999",Bachelor degree,Middle Atlantic
530,3.234766e+09,Lottery A,No,No,Yes,No,Yes,No,Yes,Well,Female,30-44,NaN,Some college or Associate degree,East South Central
531,3.234766e+09,Lottery A,No,Yes,No,No,Yes,No,Yes,Medium Well,Male,> 60,"$150,000+",Graduate degree,Pacific
532,3.234766e+09,Lottery B,Yes,Yes,Yes,No,Yes,Yes,No,NaN,Female,30-44,"$0 - $24,999",Graduate degree,Pacific
533,3.234765e+09,Lottery A,No,No,No,No,No,No,No,NaN,Female,45-60,"$25,000 - $49,999",High school degree,Pacific
534,3.234765e+09,Lottery A,No,Yes,No,No,Yes,No,Yes,Medium rare,Male,> 60,"$150,000+",Bachelor degree,Middle Atlantic
535,3.234764e+09,Lottery B,Yes,Yes,Yes,Yes,Yes,No,Yes,Medium Well,Male,45-60,"$100,000 - $149,999",Some college or Associate degree,South Atlantic
536,3.234764e+09,Lottery B,No,Yes,No,No,Yes,No,Yes,Medium rare,Female,45-60,NaN,Some college or Associate degree,Pacific
537,3.234764e+09,Lottery A,No,Yes,No,No,Yes,Yes,No,NaN,Male,45-60,"$50,000 - $99,999",Bachelor degree,West South Central
538,3.234764e+09,Lottery B,Yes,Yes,Yes,No,Yes,No,Yes,Medium rare,Female,18-29,"$50,000 - $99,999",Some college or Associate degree,Mountain
539,3.234764e+09,Lottery A,No,Yes,Yes,No,Yes,No,Yes,Medium,Male,30-44,"$100,000 - $149,999",Bachelor degree,South Atlantic
540,3.234764e+09,Lottery A,No,No,No,No,Yes,No,No,NaN,Male,45-60,"$100,000 - $149,999",Some college or Associate degree,South Atlantic
541,3.234763e+09,Lottery A,No,Yes,Yes,No,Yes,No,Yes,Medium,Male,> 60,NaN,Graduate degree,Pacific
542,3.234763e+09,Lottery B,No,No,No,No,Yes,No,No,NaN,Male,18-29,"$50,000 - $99,999",Some college or Associate degree,West North Central
543,3.234763e+09,Lottery A,No,Yes,Yes,No,Yes,No,Yes,Medium rare,Male,> 60,"$50,000 - $99,999",Bachelor degree,Pacific
544,3.234762e+09,Lottery B,No,Yes,No,No,Yes,No,Yes,Medium Well,Female,> 60,"$100,000 - $149,999",Bachelor degree,West North Central
545,3.234762e+09,Lottery A,No,No,Yes,No,Yes,No,Yes,Medium Well,Male,30-44,"$50,000 - $99,999",Graduate degree,Pacific
546,3.234762e+09,Lottery B,No,No,No,No,Yes,No,Yes,Medium rare,Female,18-29,"$25,000 - $49,999",High school degree,South Atlantic
547,3.234762e+09,Lottery A,No,Yes,No,Yes,Yes,No,No,NaN,Female,> 60,"$50,000 - $99,999",Some college or Associate degree,Mountain
548,3.234761e+09,Lottery A,Yes,Yes,Yes,No,Yes,No,Yes,Medium rare,Male,30-44,"$50,000 - $99,999",Some college or Associate degree,South Atlantic
549,3.234761e+09,Lottery A,No,Yes,Yes,No,Yes,Yes,No,NaN,Female,45-60,"$50,000 - $99,999",Some college or Associate degree,Pacific
550,3.234760e+09,Lottery B,Yes,Yes,Yes,No,Yes,No,Yes,Medium,Male,18-29,"$0 - $24,999",NaN,Mountain